# Generated by Django 2.0.5 on 2018-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2048)),
                ('fork', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('homepage', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField()),
                ('language', models.CharField(max_length=32)),
                ('open_issues', models.IntegerField()),
                ('watchers', models.IntegerField()),
            ],
        ),
    ]
