# Generated by Django 2.0.5 on 2018-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='git_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='html_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
